// Code generated by "stringer -type=AddressSetName"; DO NOT EDIT.

package settings

import "strconv"

const _AddressSetName_name = "ThirdPartyReservesOldNetWorksOldBurners"

var _AddressSetName_index = [...]uint8{0, 18, 29, 39}

func (i AddressSetName) String() string {
	if i < 0 || i >= AddressSetName(len(_AddressSetName_index)-1) {
		return "AddressSetName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddressSetName_name[_AddressSetName_index[i]:_AddressSetName_index[i+1]]
}
